#!/usr/bin/env bun
/**
 * Reads cocktails from SQLite (museum) or drinks.json, writes Postgres upsert SQL for
 * `public.cocktails`. Apply to the linked Supabase project with:
 *
 *   bunx supabase db query --linked -f supabase/.temp/cocktails_from_sqlite.sql
 *
 * Or: `bun run cocktails:upload:cli`
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadCocktailSeedRows } from "../src/lib/cocktailSeedRows.ts";

const OUT = path.join(process.cwd(), "supabase", ".temp", "cocktails_from_sqlite.sql");

function pgQuote(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

async function main(): Promise<void> {
  const rows = await loadCocktailSeedRows({ logSource: true });
  await mkdir(path.dirname(OUT), { recursive: true });

  const lines: string[] = [
    "-- Generated by scripts/generate-supabase-cocktails-sql.ts — do not edit by hand.",
    "begin;",
    "",
    "insert into public.cocktails (id_drink, name)",
    "values",
  ];

  const valueLines = rows.map(
    r => `  (${pgQuote(r.id_drink)}, ${pgQuote(r.name)})`,
  );
  lines.push(valueLines.join(",\n"));
  lines.push("on conflict (id_drink) do update set");
  lines.push("  name = excluded.name,");
  lines.push("  updated_at = now();");
  lines.push("");
  lines.push("commit;");

  await writeFile(OUT, `${lines.join("\n")}\n`, "utf8");
  console.log(`Wrote ${rows.length} rows to ${OUT}`);
  console.log("Run: bunx supabase db query --linked -f supabase/.temp/cocktails_from_sqlite.sql");
}

main().catch(err => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
